package ch.ost.cal.ade.plugins.archunit.compile;

import ch.ost.cal.ade.plugins.archunit.data.ArchUnitTestsCollection;
import ch.ost.cal.ade.plugins.archunit.data.ArchUnitTestData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class RendererTest {


    private ArchUnitTestsCollection singleTest(boolean isWarning) {
        ArchUnitTestData test = new ArchUnitTestData.Builder("ADR_001_no_deps")
                .withClassesExpr("noClasses()")
                .withPredicatesChain("            .resideInAPackage(\"com.example.app..\")")
                .withConditionChain("dependOnClassesThat().resideInAnyPackage(\"com.example.domain..\")")
                .withAdrId("ADR-001")
                .withAdrTitle("Layered Architecture")
                .withRuleName("no_deps")
                .withWarning(isWarning)
                .build();
        return new ArchUnitTestsCollection.Builder("ADR-001")
                .withAdrTitle("Layered Architecture")
                .withAdrClassName("ArchitectureFrom_ADR_001Test")
                .withArchTests(List.of(test))
                .withSkippedRules(List.of())
                .withImportedPackages("\"com.example\"")
                .withPackageName("generated.arch")
                .build();
    }

    private String render(ArchUnitTestsCollection testsCollection) throws IOException {
        return new String(new Renderer().render(testsCollection), StandardCharsets.UTF_8);
    }


    @Test
    void render_producesDoNotEditHeader() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content).startsWith("// Code generated by ad-plugin-archunit; DO NOT EDIT.");
    }

    @Test
    void render_producesCorrectPackageDeclaration() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content).contains("package generated.arch;");
    }

    @Test
    void render_importsArchUnitAndJUnit5() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("import com.tngtech.archunit.core.domain.JavaClasses;")
                .contains("import com.tngtech.archunit.core.importer.ClassFileImporter;")
                .contains("import com.tngtech.archunit.lang.ArchRule;")
                .contains("import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;")
                .contains("import org.junit.jupiter.api.Test;");
    }

    @Test
    void render_generatesPublicClassWithCorrectName() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content).contains("public class ArchitectureFrom_ADR_001Test {");
    }


    @Test
    void render_generatesAnnotatedTestMethodWithCorrectName() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("@Test")
                .contains("public void ADR_001_no_deps()");
    }

    @Test
    void render_generatesImportPackagesFromConfig() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content).contains("new ClassFileImporter().importPackages(\"com.example\")");
    }

    @Test
    void render_generatesArchRuleWithPredicateAndCondition() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("noClasses()")
                .contains(".that()")
                .contains(".resideInAPackage(\"com.example.app..\")")
                .contains(".should()")
                .contains(".dependOnClassesThat().resideInAnyPackage(\"com.example.domain..\")");
    }

    @Test
    void render_errorSeverity_usesDirectRuleCheck() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("rule.check(importedClasses);")
                .doesNotContain("try {");
    }


    @Test
    void render_warningSeverity_wrapsCheckInTryCatch() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(true);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("try {")
                .contains("rule.check(importedClasses);")
                .contains("} catch (AssertionError e) {")
                .contains("WARN:");
    }

    @Test
    void render_warningSeverity_includesAdrAndRuleInWarnMessage() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(true);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("ADR-001")
                .contains("no_deps");
    }


    @Test
    void render_skippedRules_appearsAsCommentBlock() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = new ArchUnitTestsCollection.Builder("ADR-001")
                .withAdrTitle("Test")
                .withAdrClassName("ArchitectureFrom_ADR_001Test")
                .withArchTests(List.of())
                .withSkippedRules(List.of("no_cycles (ACYCLIC: cycle detection requires a custom rule)"))
                .withImportedPackages("\"com.example\"")
                .withPackageName("generated")
                .build();

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("// The following rules could not be expressed via ArchUnit and were skipped:")
                .contains("//   - no_cycles (ACYCLIC:");
    }

    @Test
    void render_noSkippedRules_commentBlockIsAbsent() throws IOException {
        // given
        ArchUnitTestsCollection testsCollection = singleTest(false);

        // when
        String content = render(testsCollection);

        // then
        assertThat(content).doesNotContain("// The following rules could not be expressed");
    }


    @Test
    void render_multipleTests_allMethodsAppearInOutput() throws IOException {
        // given
        ArchUnitTestData testDataA = new ArchUnitTestData.Builder("ADR_001_rule_a")
                .withClassesExpr("noClasses()")
                .withPredicatesChain("            .resideInAPackage(\"com.example.web..\")")
                .withConditionChain("dependOnClassesThat().resideInAnyPackage(\"com.example.domain..\")")
                .withAdrId("ADR-001").withAdrTitle("Test").withRuleName("rule_a")
                .build();
        ArchUnitTestData testDataB = new ArchUnitTestData.Builder("ADR_001_rule_b")
                .withClassesExpr("classes()")
                .withPredicatesChain("            .resideInAPackage(\"com.example.service..\")")
                .withConditionChain("bePublic()")
                .withAdrId("ADR-001").withAdrTitle("Test").withRuleName("rule_b")
                .build();
        ArchUnitTestsCollection testsCollection = new ArchUnitTestsCollection.Builder("ADR-001")
                .withAdrTitle("Test")
                .withAdrClassName("ArchitectureFrom_ADR_001Test")
                .withArchTests(List.of(testDataA, testDataB))
                .withSkippedRules(List.of())
                .withImportedPackages("\"com.example\"")
                .withPackageName("generated")
                .build();

        // when
        String content = render(testsCollection);

        // then
        assertThat(content)
                .contains("public void ADR_001_rule_a()")
                .contains("public void ADR_001_rule_b()");
    }
}
