package ch.ost.cal.ade.plugins.archunit;

import ch.ost.cal.ade.plugins.archunit.compile.Compiler;
import ch.ost.cal.ade.plugins.archunit.exceptions.BuildException;
import ch.ost.cal.ade.plugins.archunit.spec.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests that exercise the full plugin pipeline from a Spec
 * protobuf (the in-memory equivalent of a parsed .rule file) through to
 * a generated ArchUnit test source file.
 */
class ArchUnitPluginIntegrationTest {

    @Test
    void compile_layeredArchitecture_generatesCorrectTestFile(@TempDir Path outputDir)
            throws BuildException, IOException {

        // given — the scenario from sample.rule: ADR 0001 with two layers and one file rule
        Spec spec = layeredArchTestSpec(outputDir);

        // when
        new Compiler(spec).run();

        // then — the generated file exists with correct structure
        Path generated = outputDir.resolve("ArchitectureFrom_0001Test.java");
        assertThat(generated).exists();

        String content = Files.readString(generated);

        assertThat(content)
                .as("do-not-edit header")
                .startsWith("// Code generated by ad-plugin-archunit; DO NOT EDIT.");

        assertThat(content)
                .as("package from plugin config")
                .contains("package generated.arch;");

        assertThat(content)
                .as("class name derived from ADR id '0001'")
                .contains("public class ArchitectureFrom_0001Test");

        assertThat(content)
                .as("test method for the 'no_upward_deps' code rule")
                .contains("@Test")
                .contains("public void R_0001_no_upward_deps()");

        assertThat(content)
                .as("Domain must not depend on App")
                .contains("noClasses()")
                .contains(".that()")
                .contains(".resideInAPackage(\"com.example.domain..\")")
                .contains(".should()")
                .contains(".dependOnClassesThat().resideInAnyPackage(\"com.example.app..\")");

        assertThat(content)
                .as("Whole applications slices must be acyclic")
                .contains("slices()")
                .contains(".matching(\"com.example.(*)..\")")
                .contains(".should()")
                .contains(".beFreeOfCycles()");

        assertThat(content)
                .as("packages to scan come from archunit.import-packages config")
                .contains("importPackages(\"com.example\")");

        assertThat(content)
                .as("file rule 'readme_exists' must be silently ignored")
                .doesNotContain("readme_exists");
    }

    @Test
    void compile_warningSeverityRule_generatesAssumptionPattern(@TempDir Path outputDir)
            throws BuildException, IOException {

        // given
        Spec spec = Spec.newBuilder()
                .setMode(InvocationMode.MODE_COMPILE)
                .setAdr(Adr.newBuilder().setId("ADR-002").setTitle("Warning Test").build())
                .addSelectors(component("Service", "com.example.service"))
                .addSelectors(component("Domain", "com.example.domain"))
                .addRules(Rule.newBuilder()
                        .setName("soft_check").setKind(RuleKind.RULE_NOT_DEPEND)
                        .setFrom(selRef("Service")).addTargets(selRef("Domain"))
                        .setSeverity(Severity.SEVERITY_WARNING)
                        .build())
                .putPluginConfig("archunit.import-packages", "com.example")
                .putPluginConfig("archunit.package", "generated")
                .putPluginConfig("output-dir", outputDir.toString())
                .build();

        // when
        new Compiler(spec).run();

        // then — warning rules are wrapped in try/catch instead of failing hard
        String content = Files.readString(outputDir.resolve("ArchitectureFrom_ADR_002Test.java"));
        assertThat(content)
                .contains("try {")
                .contains("rule.check(importedClasses);")
                .contains("} catch (AssertionError e) {")
                .contains("WARN:");
    }

    @Test
    void compile_dependOnly_forbidsAllNonAllowedPackages(@TempDir Path outputDir)
            throws BuildException, IOException {

        // given — Web may only depend on Service; Domain and Infra must become forbidden
        Spec spec = Spec.newBuilder()
                .setMode(InvocationMode.MODE_COMPILE)
                .setAdr(Adr.newBuilder().setId("ADR-004").setTitle("Strict Layers").build())
                .addSelectors(component("Web", "com.example.web"))
                .addSelectors(component("Service", "com.example.service"))
                .addSelectors(component("Domain", "com.example.domain"))
                .addSelectors(component("Infra", "com.example.infra"))
                .addRules(Rule.newBuilder()
                        .setName("web_only_service").setKind(RuleKind.RULE_DEPEND_ONLY)
                        .setFrom(selRef("Web")).addTargets(selRef("Service"))
                        .setSeverity(Severity.SEVERITY_ERROR)
                        .build())
                .putPluginConfig("import-packages", "com.example")
                .putPluginConfig("generated-tests-package", "generated")
                .putPluginConfig("output-dir", outputDir.toString())
                .build();

        // when
        new Compiler(spec).run();

        // then — forbidden set is exactly Domain + Infra (sorted)
        String content = Files.readString(outputDir.resolve("ArchitectureFrom_ADR_004Test.java"));
        assertThat(content)
                .as("both non-allowed packages must appear in the condition")
                .contains("dependOnClassesThat().resideInAnyPackage(" +
                        "\"com.example.domain..\", \"com.example.infra..\")");
        assertThat(content)
                .as("the allowed selector must not appear as a forbidden target")
                .doesNotContain("com.example.service..");
    }

    @Test
    void info_outputsValidJsonDescriptor() {
        // given
        PrintStream originalOut = System.out;
        ByteArrayOutputStream capture = new ByteArrayOutputStream();
        System.setOut(new PrintStream(capture));

        try {
            // when
            int exitCode = new ArchUnitPlugin().run(new String[]{"--info"});

            // then
            assertThat(exitCode).isEqualTo(0);
            assertThat(capture.toString())
                    .contains("\"modes\"")
                    .contains("\"compile\"")
                    .contains("\"verify\"")
                    .contains("\"config_prefix\":\"archunit\"")
                    .contains("\"version\"");
        } finally {
            System.setOut(originalOut);
        }
    }

    private Spec layeredArchTestSpec(Path outputDir) {
        return Spec.newBuilder()
                .setMode(InvocationMode.MODE_COMPILE)
                .setAdr(Adr.newBuilder().setId("0001").setTitle("Use Layered Architecture").build())
                .addSelectors(component("CompleteApp", "com.example"))
                .addSelectors(component("Domain", "com.example.domain"))
                .addSelectors(component("App", "com.example.app"))
                .addRules(Rule.newBuilder()
                        .setName("no_upward_deps").setKind(RuleKind.RULE_NOT_DEPEND)
                        .setFrom(selRef("Domain")).addTargets(selRef("App"))
                        .setSeverity(Severity.SEVERITY_ERROR)
                        .build())
                .addRules(Rule.newBuilder()
                        .setName("no_cycles").setKind(RuleKind.RULE_ACYCLIC)
                        .setFrom(selRef("CompleteApp"))
                        .setSeverity(Severity.SEVERITY_ERROR)
                        .build())
                .addRules(Rule.newBuilder().setName("readme_exists").setIsFileRule(true).build())
                .putPluginConfig("import-packages", "com.example")
                .putPluginConfig("generated-tests-package", "generated.arch")
                .putPluginConfig("output-dir", outputDir.toString())
                .build();
    }

    private Selector component(String name, String pattern) {
        return Selector.newBuilder()
                .setName(name).setPattern(pattern).setKind(SelectorKind.SELECTOR_COMPONENT).build();
    }

    private TargetRef selRef(String selectorName) {
        return TargetRef.newBuilder().setIsInline(false).setValue(selectorName).build();
    }
}
