// Code generated by ad-plugin-archunit; DO NOT EDIT.
package ${packageName};

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.lang.ArchRule;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;
import org.junit.jupiter.api.Test;

public class ${adrClassName} {
<#list archTests as t>

    @Test
    public void ${t.testMethodName}() {
        JavaClasses importedClasses = new ClassFileImporter().importPackages(${importedPackages});

<#if t.isSlices>
        ArchRule rule = slices()
            .matching(${t.predicatesChain})
<#else>
        ArchRule rule = ${t.classesExpr}
            .that()
${t.predicatesChain}
</#if>
            .should()
            .${t.conditionChain};

<#if t.isWarning>
        try {
            rule.check(importedClasses);
        } catch (AssertionError e) {
            System.err.println("WARN: ADR ${t.adrId?j_string} (${t.adrTitle?j_string}), rule ${t.ruleName?j_string} violated: " + e.getMessage());
        }
<#else>
        rule.check(importedClasses);
</#if>
    }
</#list>
<#if hasSkipped>

    // The following rules could not be expressed via ArchUnit and were skipped:
<#list skippedRules as r>
    //   - ${r}
</#list>
</#if>
}
